apiVersion: v1
kind: ServiceAccount
metadata:
  name: main
  annotations:
    helm.sh/hook-weight: "-10"
---

apiVersion: v1
kind: Pod
metadata:
  name: main
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  serviceAccountName: main
  containers:
    - name: main
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'sleep infinity']
      volumeMounts:
        - mountPath: /test
          name: test
  volumes:
    - name: test
      secret:
        secretName: main
---
apiVersion: v1
kind: Secret
metadata:
  name: main
data:
  value: {{print "main" | b64enc }}
