apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-install-hook-1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
---

apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-hook-1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      serviceAccountName: pre-install-hook-1
      containers:
        - name: pre-install
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo pre-install-job-hook-1 running, weight -2 ; sleep 10']
          volumeMounts:
            - mountPath: /test
              name: test
      volumes:
        - name: test
          secret:
            secretName: pre-install-hook-1
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: pre-install-hook-1
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-2"
data:
  value: {{print "pre-install-hook-1" | b64enc }}